language: node_js
node_js:
  - '8'
git:
  depth: 5
branches:
  only:
  - master
  - /^(\d+\.){2}\d+$/
before_script: node ./scripts/tag-update $TRAVIS_TAG
deploy:
  - provider: npm
    skip_cleanup: true
    email: alisahinozcelik@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
      repo: gen-tech/angular-rest
